sudo: required

services:
  - docker

before_install:
  - docker pull gbraad/flatpak

install:
  - docker run -it --volume=$(pwd):/data:rw gbraad/flatpak 'make --directory=/data remotes'
  - docker run -it --volume=$(pwd):/data:rw gbraad/flatpak 'make --directory=/data deps'

script:
  - docker run -it --volume=$(pwd):/data:rw gbraad/flatpak 'make --directory=/data build'
  - docker run -it --volume=$(pwd):/data:rw gbraad/flatpak 'make --directory=/data bundle'