sudo: required

services:
  - docker

before_install:
  - docker pull gbraad/flatpak

install:
  - docker run -it --rm=false --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak sh -c 'dnf --assumeyes install make'
  - docker run -it --rm=false --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak sh -c 'ls -ahls /data'
  - docker run -it --rm=false --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak sh -c 'make --directory=/data remotes'
  - docker run -it --rm=false --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak sh -c 'make --directory=/data deps'

script:
  - docker run -it --rm=false --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak sh -c 'make --directory=/data build'
  - docker run -it --rm=false --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak sh -c 'make --directory=/data bundle'