sudo: required
before_install:
  - sudo add-apt-repository -y ppa:alexlarsson/flatpak
  - sudo apt-get -q update
  - sudo apt-get install flatpack

install:
  - make remotes
  - make deps

script:
  - make build
  - make bundle