sudo: required

services:
  - docker

before_install:
  - docker pull gbraad/flatpak

install:
  - docker run -it --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak 'ls -ahls /'
  - docker run -it --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak 'ls -ahls /data'
  - docker run -it --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak 'make --directory=/data remotes'
  - docker run -it --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak 'make --directory=/data deps'

script:
  - docker run -it --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak 'make --directory=/data build'
  - docker run -it --volume=$TRAVIS_BUILD_DIR:/data:rw gbraad/flatpak 'make --directory=/data bundle'